/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as PrescriptionsRouteImport } from './routes/prescriptions'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MedicationsRouteImport } from './routes/medications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CaregiverRouteImport } from './routes/caregiver'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientDashboardRouteImport } from './routes/patient.dashboard'

const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionsRoute = PrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicationsRoute = MedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiverRoute = CaregiverRouteImport.update({
  id: '/caregiver',
  path: '/caregiver',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientDashboardRoute = PatientDashboardRouteImport.update({
  id: '/patient/dashboard',
  path: '/patient/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/caregiver': typeof CaregiverRoute
  '/dashboard': typeof DashboardRoute
  '/doctor': typeof DoctorRoute
  '/login': typeof LoginRoute
  '/medications': typeof MedicationsRoute
  '/onboarding': typeof OnboardingRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/reminders': typeof RemindersRoute
  '/patient/dashboard': typeof PatientDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/caregiver': typeof CaregiverRoute
  '/dashboard': typeof DashboardRoute
  '/doctor': typeof DoctorRoute
  '/login': typeof LoginRoute
  '/medications': typeof MedicationsRoute
  '/onboarding': typeof OnboardingRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/reminders': typeof RemindersRoute
  '/patient/dashboard': typeof PatientDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/caregiver': typeof CaregiverRoute
  '/dashboard': typeof DashboardRoute
  '/doctor': typeof DoctorRoute
  '/login': typeof LoginRoute
  '/medications': typeof MedicationsRoute
  '/onboarding': typeof OnboardingRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/reminders': typeof RemindersRoute
  '/patient/dashboard': typeof PatientDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/caregiver'
    | '/dashboard'
    | '/doctor'
    | '/login'
    | '/medications'
    | '/onboarding'
    | '/prescriptions'
    | '/reminders'
    | '/patient/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/caregiver'
    | '/dashboard'
    | '/doctor'
    | '/login'
    | '/medications'
    | '/onboarding'
    | '/prescriptions'
    | '/reminders'
    | '/patient/dashboard'
  id:
    | '__root__'
    | '/'
    | '/caregiver'
    | '/dashboard'
    | '/doctor'
    | '/login'
    | '/medications'
    | '/onboarding'
    | '/prescriptions'
    | '/reminders'
    | '/patient/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaregiverRoute: typeof CaregiverRoute
  DashboardRoute: typeof DashboardRoute
  DoctorRoute: typeof DoctorRoute
  LoginRoute: typeof LoginRoute
  MedicationsRoute: typeof MedicationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PrescriptionsRoute: typeof PrescriptionsRoute
  RemindersRoute: typeof RemindersRoute
  PatientDashboardRoute: typeof PatientDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescriptions': {
      id: '/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof PrescriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medications': {
      id: '/medications'
      path: '/medications'
      fullPath: '/medications'
      preLoaderRoute: typeof MedicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregiver': {
      id: '/caregiver'
      path: '/caregiver'
      fullPath: '/caregiver'
      preLoaderRoute: typeof CaregiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/dashboard': {
      id: '/patient/dashboard'
      path: '/patient/dashboard'
      fullPath: '/patient/dashboard'
      preLoaderRoute: typeof PatientDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaregiverRoute: CaregiverRoute,
  DashboardRoute: DashboardRoute,
  DoctorRoute: DoctorRoute,
  LoginRoute: LoginRoute,
  MedicationsRoute: MedicationsRoute,
  OnboardingRoute: OnboardingRoute,
  PrescriptionsRoute: PrescriptionsRoute,
  RemindersRoute: RemindersRoute,
  PatientDashboardRoute: PatientDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
